In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [3]:
 training_input = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

In [4]:
training_output = np.array([[0,1,1,0]]).T

In [5]:
print (training_input)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]


In [6]:
print(training_output)

[[0]
 [1]
 [1]
 [0]]


In [7]:
#menghasilkan 3 nilai berat secara random
np.random.seed(1)
synaptic_weights = 2 * np.random.random((3,1)) - 1

In [8]:
print(synaptic_weights)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [9]:
#jadi begini 
a = [[1, 1,1],
     [1, 0,1],
     [1, 0,1]]
b = [[4], 
     [2],
     [3]]

np.dot(a, b)

array([[9],
       [7],
       [7]])

In [10]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [11]:

for iteration in range (20000):
    input_layer = training_input
    input_sigmoid = np.dot(input_layer, synaptic_weights)
    output = sigmoid(input_sigmoid)
    error = training_output - output  
    adjustments = error * sigmoid_derivative(output)   
    synaptic_weights += np.dot(input_layer.T , adjustments)
    
print('synaptic_weights after training: ')
print(synaptic_weights)

print('Output after training: ')
print(output)
    

synaptic_weights after training: 
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Output after training: 
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]
